/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "9c10df3b60f4a7d50c1070a5d8c4aaadb79ba9b7"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
